services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: leadmanagement-db-container
    environment:
      SA_PASSWORD: "Password1234!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./backup.sql:/tmp/backup.sql
      - ./init-database.sh:/tmp/init-database.sh
    command: /bin/bash /tmp/init-database.sh
